FROM node:8.10.0-slim
MAINTAINER Joe

RUN mkdir -p /runDIR/web
WORKDIR /runDIR/web

COPY ./ /runDIR/web 
RUN cd /runDIR/web && npm install
RUN cd /runDIR/web && npm run build

ENV HOST 0.0.0.0
ENV PORT 8080
ENV NODE_ENV production

EXPOSE 8080
ENTRYPOINT ["npm","start"]
