FROM java:8-jdk-alpine

RUN mkdir -p /deployment/
RUN mkdir -p /app/
ADD ./target/*.jar /deployment/
RUN cd /deployment/ && mv ./*.jar /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]

