
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: <%=data.deploymentName%>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <%=data.applicationName%>
  template:
    metadata:
      labels:
        app: <%=data.applicationName%>
    spec:
      containers:
      - name: <%=data.applicationName%> 
        image: <%=data.imageName%>
        ports:
        - containerPort: 80
        envFrom:
            - configMapRef:
                name: common-config
        volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/simple
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
    
     
---
apiVersion: v1
kind: Service
metadata:
  name: <%=data.serviceName%>
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: <%=data.applicationName%>
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: <%=data.certConfigName%> 
spec:
  dnsNames:
    - <%=data.gateway%>
  secretName: <%=data.certConfigName%> 
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: <%=data.ingressName%>
spec:
  ingressClassName: nginx
  rules:
  - host: <%=data.gateway%>
    http:
      paths: <%data.routes.forEach(function(route){%>
      - path: <%=route.path%>
        pathType: Prefix
        backend:
          serviceName: <%=route.serviceName%>
          servicePort: 80<%});%>