version: '3.7'

services:
  xcoder-service:
    #build: ./account-svc
    image: registry.cn-hangzhou.aliyuncs.com/windwithlife/xcoder-server:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=80  
    depends_on:
      - mysql-server
    networks:
      - internal_access
      - external_access # db access 
  mysql-server:
    image: windwithlife/xmysql:latest
    ports:
      - '33066:3306'
    volumes:
      - /data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password!&
      - MYSQL_DATABASE=mydb
    networks:
      - internal_access

  www-service:
    build:
      context: ./
      dockerfile: web/Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/windwithlife/xcoder-web:v1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - xcoder-service
    networks:
      - internal_access
      - external_access # db access
networks:
  internal_access:
    internal: true
  external_access:

