version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro 
      - ./nginx/logs/:/etc/nginx/logs/ 
      - ./nginx/www/html:/var/www/html/
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=80  
    depends_on:
      - mysql-server
      - xcoder-service
      - www-service
    networks:
      - internal_access
      - external_access # db access
  xcoder-service:
    build:
      context: ./server/javaserver/
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/windwithlife/xcoder-server:v1
    ports:
      - '9999:80'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=80  
    depends_on:
      - mysql-server
    networks:
      - internal_access
      - external_access # db access 
  mysql-server:
    image: windwithlife/xmysql:latest
    ports:
      - '33066:3306'
    
    environment:
      - MYSQL_ROOT_PASSWORD=Password!&
      - MYSQL_DATABASE=mydb
    networks:
      - internal_access
      - external_access # db access

  www-service:
    build:
      context: ./web/
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/windwithlife/xcoder-web:v1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - xcoder-service
      - mysql-server
    networks:
      - internal_access
      - external_access # db access
networks:
  internal_access:
    internal: true
  external_access:

