logging:
  config: /etc/simple/logback-spring.xml


spring:
  datasource:
    url: jdbc:mysql://test.koudaibook.com:30006/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: manager.e-healthcare.net
    password: meetinglive
    port: 31379
  mqtt:
    server:
      username: ""
      password: ""
      url:  tcp://mq.koudaibook.com:30883
    client:
      publishId: "publish-id"
      subscribeId: "subscribe-id"
    default:
      topic: "ci/simple/center/soa-server/#"
      completionTimeout: 3000

server:
  servlet:
    context-path: /simple/deployment
simple:
  domainName: koudaibook.com

qiniu:
  accessKey: JMVsA4svqk_TUAjq9jOKy0fLVxBaJpiaAAhcn0gr
  secretKey: 39xrdVIpTa65jjPkAB9RCjzdDKN_VY4KdcPkhNjD
  bucket: windwithlife
  domainName: http://images.koudaibook.com