# application.yml

spring:
  profiles:
    active: dev
  application:
    name: example-service
  datasource:
    url: ${NEWS_DATASOURCE_URL}
    username: ${NEWS_DATASOURCE_USERNAME}
    password: ${NEWS_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1

simple:
  common:
    sentry-dsn: ${SENTRY_DSN}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}

server:
  servlet:
    context-path: /simple/deployment