apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-redis
  labels:
    k8s-app: my-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: my-redis
  template:
    metadata:
      labels:
        k8s-app: my-redis
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
        resourceType: enough
      #hostNetwork: true
      containers:
      - name: redis
        image: docker.io/redis
        ports:
        - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    k8s-app: database-redis
spec:
  type: NodePort
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
    nodePort: 30379
  selector:
    k8s-app: my-redis
