apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xcoder-endpoint
spec:
  template:
    metadata: 
      name: xcoder-endpoint
      namespace: default
      labels:
        k8sApp: xcoder-endpoint 
    spec: 
      #hostNetwork: true
      containers: 
      - name: xci-website-container 
        image: xci-web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3333
        volumeMounts: 
          - mountPath: /var/run 
            name: docker-sock 
          - mountPath: /usr/bin/docker 
            name: docker-bin 
          - mountPath: /usr/bin/kubectl 
            name: kubectl-bin 
          - mountPath: /root/.kube/config 
            name: kubectl-conf 
      volumes: 
      - name: docker-sock 
        hostPath: 
            path: /var/run 
      - name: docker-bin 
        hostPath: 
            path: /usr/bin/docker 
      - name: kubectl-bin 
        hostPath: 
            path: /usr/bin/kubectl 
      - name: kubectl-conf 
        hostPath: 
            path: /root/.kube/config
---
apiVersion: v1
kind: Service
metadata:
  name: xcoder-endpoint-svc
  namespace: default
  labels:
    k8sApp: xcoder-endpoint-svc
spec:
  selector:
    k8sApp: xcoder-endpoint
  ports:
    - port: 80
      targetPort: 8080
---

