spring:
  datasource:
    url: jdbc:mysql://test.koudaibook.com:30006/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&
  jpa:
    show-sql: true
server:
  port: 8081
staffjoy:
  email-service-endpoint: http://localhost:8088
management:
  endpoints:
    web:
      exposure:
        include: "*"
