spring:
  datasource:
    url: jdbc:mysql://test.koudaibook.com:30006/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
 #   driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8888
staffjoy:
  account-service-endpoint: http://localhost:8081
  email-service-endpoint: http://localhost:8088
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
