spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&
    initialization-mode: always
    continue-on-error: true
    data: classpath:dictionary.sql
 #   driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 80
simple:
  account-service-endpoint: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
