
application:  
  name: deploycenter
  service:
    port: 8080
    contextPath: /xcoder
    routerPath : /xcoder
servers:
  soaServer: http://localhost:9999
  mqServer : mqtt://localhost:8083/mqtt
  releasesServer: http://localhost:8080
repositories:
  docker: registry.cn-hangzhou.aliyuncs.com/windwithlife/
  


 
  