
application:  
  name: deploycenter
  service:
    port: 8080
    contextPath: /xcoder
    routerPath : /xcoder
servers:
  soaServer: http://soagateway.koudaibook.com
  mqServer : mqtt://mq.koudaibook.com:30083/ws
repositories:
  docker: registry.cn-hangzhou.aliyuncs.com/windwithlife/
  


 
  