
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: tea 
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: 

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: services-ingress
spec:
  tls:
  - hosts:
    - gateway.koudaibook.com
    secretName: one-cert
  rules:
  - host: gateway.koudaibook.com
    http:
      paths:
      - path: medicallive
        backend:
          serviceName: test-service
          servicePort: 80
      - path: medicallive234
        backend:
          serviceName: test-service23
          servicePort: 80