
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8sApp: <%=data.deploymentName%>
  name:  <%=data.deploymentName%>
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      k8sApp:  <%=data.applicationName%>
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8sApp: <%=data.applicationName%>
    spec:
      nodeSelector:
        resourceType: enough
      containers:
      - image: <%-data.imageName%>
        imagePullPolicy: IfNotPresent
        name: <%=data.applicationName%>
        ports:
        - containerPort: 8080
          protocol: TCP

      dnsPolicy: ClusterFirst
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: <%=data.serviceName%>
  namespace: default
  labels:
    k8sApp: <%=data.serviceName%>
spec:

  selector:
    k8sApp: <%=data.serviceName%>
  ports:
  - port: 8080
    targetPort: 8080


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <%=data.ingressName%>
  annotations:
    #ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: gateway.koudaibook.com
    http:
      paths:
      - path: /<%=data.serviceName%>
        backend:
          serviceName: <%=data.serviceName%>
          servicePort: 8080
